import '../../Util/app_imports.dart';

class RamadanCubit extends Cubit<RamadanState> {
  RamadanCubit() : super(RamadanInitial());

  void loadRamadan() {
    try {
      emit(RamadanLoading());

      // تحويل البيانات من Map إلى RamadanDay objects
      final days =
          ramadanScheduleData.map((data) => RamadanDay.fromJson(data)).toList();

      emit(RamadanLoaded(days));
    } catch (e) {
      emit(RamadanError('حدث خطأ في تحميل البيانات: $e'));
    }
  }

  List<Map<String, dynamic>> ramadanScheduleData = [
    {
      'day': 1,
      'weekday': 'الخميس',
      'gregorianDate': '19',
      'hijriDate': '1 رمضان',
      'imsak': '4:56',
      'fajr': '5:05',
      'sunrise': '6:19',
      'dhuhr': '11:52',
      'maghrib': '5:44',
    },
    {
      'day': 2,
      'weekday': 'الجمعة',
      'gregorianDate': '20',
      'hijriDate': '2',
      'imsak': '4:55',
      'fajr': '5:04',
      'sunrise': '6:18',
      'dhuhr': '11:52',
      'maghrib': '5:45',
    },
    {
      'day': 3,
      'weekday': 'السبت',
      'gregorianDate': '21',
      'hijriDate': '3',
      'imsak': '4:54',
      'fajr': '5:03',
      'sunrise': '6:16',
      'dhuhr': '11:52',
      'maghrib': '5:45',
    },
    {
      'day': 4,
      'weekday': 'الأحد',
      'gregorianDate': '22',
      'hijriDate': '4',
      'imsak': '4:53',
      'fajr': '5:01',
      'sunrise': '6:15',
      'dhuhr': '11:51',
      'maghrib': '5:46',
    },
    {
      'day': 5,
      'weekday': 'الإثنين',
      'gregorianDate': '23',
      'hijriDate': '5',
      'imsak': '4:52',
      'fajr': '5:00',
      'sunrise': '6:14',
      'dhuhr': '11:51',
      'maghrib': '5:47',
    },
    {
      'day': 6,
      'weekday': 'الثلاثاء',
      'gregorianDate': '24',
      'hijriDate': '6',
      'imsak': '4:51',
      'fajr': '4:59',
      'sunrise': '6:13',
      'dhuhr': '11:51',
      'maghrib': '5:48',
    },
    {
      'day': 7,
      'weekday': 'الأربعاء',
      'gregorianDate': '25',
      'hijriDate': '7',
      'imsak': '4:50',
      'fajr': '4:58',
      'sunrise': '6:12',
      'dhuhr': '11:51',
      'maghrib': '5:49',
    },
    {
      'day': 8,
      'weekday': 'الخميس',
      'gregorianDate': '26',
      'hijriDate': '8',
      'imsak': '4:49',
      'fajr': '4:57',
      'sunrise': '6:11',
      'dhuhr': '11:51',
      'maghrib': '5:50',
    },
    {
      'day': 9,
      'weekday': 'الجمعة',
      'gregorianDate': '27',
      'hijriDate': '9',
      'imsak': '4:48',
      'fajr': '4:56',
      'sunrise': '6:09',
      'dhuhr': '11:51',
      'maghrib': '5:50',
    },
    {
      'day': 10,
      'weekday': 'السبت',
      'gregorianDate': '28',
      'hijriDate': '10',
      'imsak': '4:47',
      'fajr': '4:55',
      'sunrise': '6:08',
      'dhuhr': '11:50',
      'maghrib': '5:51',
    },
    {
      'day': 11,
      'weekday': 'الأحد',
      'gregorianDate': '1 آذار',
      'hijriDate': '11',
      'imsak': '4:45',
      'fajr': '4:54',
      'sunrise': '6:07',
      'dhuhr': '11:50',
      'maghrib': '5:52',
    },
    {
      'day': 12,
      'weekday': 'الإثنين',
      'gregorianDate': '2',
      'hijriDate': '12',
      'imsak': '4:44',
      'fajr': '4:52',
      'sunrise': '6:06',
      'dhuhr': '11:50',
      'maghrib': '5:53',
    },
    {
      'day': 13,
      'weekday': 'الثلاثاء',
      'gregorianDate': '3',
      'hijriDate': '13',
      'imsak': '4:43',
      'fajr': '4:51',
      'sunrise': '6:05',
      'dhuhr': '11:50',
      'maghrib': '5:54',
    },
    {
      'day': 14,
      'weekday': 'الأربعاء',
      'gregorianDate': '4',
      'hijriDate': '14',
      'imsak': '4:42',
      'fajr': '4:50',
      'sunrise': '6:03',
      'dhuhr': '11:50',
      'maghrib': '5:54',
    },
    {
      'day': 15,
      'weekday': 'الخميس',
      'gregorianDate': '5',
      'hijriDate': '15',
      'imsak': '4:40',
      'fajr': '4:49',
      'sunrise': '6:02',
      'dhuhr': '11:49',
      'maghrib': '5:55',
    },
    {
      'day': 16,
      'weekday': 'الجمعة',
      'gregorianDate': '6',
      'hijriDate': '16',
      'imsak': '4:39',
      'fajr': '4:47',
      'sunrise': '6:01',
      'dhuhr': '11:49',
      'maghrib': '5:56',
    },
    {
      'day': 17,
      'weekday': 'السبت',
      'gregorianDate': '7',
      'hijriDate': '17',
      'imsak': '4:38',
      'fajr': '4:46',
      'sunrise': '5:59',
      'dhuhr': '11:49',
      'maghrib': '5:57',
    },
    {
      'day': 18,
      'weekday': 'الأحد',
      'gregorianDate': '8',
      'hijriDate': '18',
      'imsak': '4:37',
      'fajr': '4:45',
      'sunrise': '5:58',
      'dhuhr': '11:49',
      'maghrib': '5:58',
    },
    {
      'day': 19,
      'weekday': 'الإثنين',
      'gregorianDate': '9',
      'hijriDate': '19',
      'imsak': '4:35',
      'fajr': '4:44',
      'sunrise': '5:57',
      'dhuhr': '11:48',
      'maghrib': '5:59',
    },
    {
      'day': 20,
      'weekday': 'الثلاثاء',
      'gregorianDate': '10',
      'hijriDate': '20',
      'imsak': '4:34',
      'fajr': '4:42',
      'sunrise': '5:56',
      'dhuhr': '11:48',
      'maghrib': '5:59',
    },
    {
      'day': 21,
      'weekday': 'الأربعاء',
      'gregorianDate': '11',
      'hijriDate': '21',
      'imsak': '4:33',
      'fajr': '4:41',
      'sunrise': '5:54',
      'dhuhr': '11:48',
      'maghrib': '6:00',
    },
    {
      'day': 22,
      'weekday': 'الخميس',
      'gregorianDate': '12',
      'hijriDate': '22',
      'imsak': '4:31',
      'fajr': '4:40',
      'sunrise': '5:53',
      'dhuhr': '11:48',
      'maghrib': '6:01',
    },
    {
      'day': 23,
      'weekday': 'الجمعة',
      'gregorianDate': '13',
      'hijriDate': '23',
      'imsak': '4:30',
      'fajr': '4:38',
      'sunrise': '5:52',
      'dhuhr': '11:47',
      'maghrib': '6:02',
    },
    {
      'day': 24,
      'weekday': 'السبت',
      'gregorianDate': '14',
      'hijriDate': '24',
      'imsak': '4:29',
      'fajr': '4:37',
      'sunrise': '5:50',
      'dhuhr': '11:47',
      'maghrib': '6:02',
    },
    {
      'day': 25,
      'weekday': 'الأحد',
      'gregorianDate': '15',
      'hijriDate': '25',
      'imsak': '4:27',
      'fajr': '4:36',
      'sunrise': '5:49',
      'dhuhr': '11:47',
      'maghrib': '6:03',
    },
    {
      'day': 26,
      'weekday': 'الإثنين',
      'gregorianDate': '16',
      'hijriDate': '26',
      'imsak': '4:26',
      'fajr': '4:34',
      'sunrise': '5:48',
      'dhuhr': '11:47',
      'maghrib': '6:04',
    },
    {
      'day': 27,
      'weekday': 'الثلاثاء',
      'gregorianDate': '17',
      'hijriDate': '27',
      'imsak': '4:24',
      'fajr': '4:33',
      'sunrise': '5:46',
      'dhuhr': '11:46',
      'maghrib': '6:05',
    },
    {
      'day': 28,
      'weekday': 'الأربعاء',
      'gregorianDate': '18',
      'hijriDate': '28',
      'imsak': '4:23',
      'fajr': '4:31',
      'sunrise': '5:45',
      'dhuhr': '11:46',
      'maghrib': '6:06',
    },
    {
      'day': 29,
      'weekday': 'الخميس',
      'gregorianDate': '19',
      'hijriDate': '29',
      'imsak': '4:22',
      'fajr': '4:30',
      'sunrise': '5:44',
      'dhuhr': '11:46',
      'maghrib': '6:06',
    },
    {
      'day': 30,
      'weekday': 'الجمعة',
      'gregorianDate': '20',
      'hijriDate': '30',
      'imsak': '4:20',
      'fajr': '4:29',
      'sunrise': '5:42',
      'dhuhr': '11:45',
      'maghrib': '6:07',
    },
  ];
}
