class QuranSurah {
  late final String name;
  late int pageNumber;
  late int number;

  QuranSurah({
    required this.name,
    required this.pageNumber,
    required this.number,
  });
}

final List<QuranSurah> surahsPage = [
  QuranSurah(number: 1, name: "الفاتحة", pageNumber: 1),
  QuranSurah(number: 2, name: "البقرة", pageNumber: 2),
  QuranSurah(number: 3, name: "آل عمران", pageNumber: 50),
  QuranSurah(number: 4, name: "النساء", pageNumber: 77),
  QuranSurah(number: 5, name: "المائدة", pageNumber: 106),
  QuranSurah(number: 6, name: "الأنعام", pageNumber: 128),
  QuranSurah(number: 7, name: "الأعراف", pageNumber: 151),
  QuranSurah(number: 8, name: "الأنفال", pageNumber: 177),
  QuranSurah(number: 9, name: "التوبة", pageNumber: 187),
  QuranSurah(number: 10, name: "يونس", pageNumber: 208),
  QuranSurah(number: 11, name: "هود", pageNumber: 221),
  QuranSurah(number: 12, name: "يوسف", pageNumber: 235),
  QuranSurah(number: 13, name: "الرعد", pageNumber: 249),
  QuranSurah(number: 14, name: "إبراهيم", pageNumber: 255),
  QuranSurah(number: 15, name: "الحجر", pageNumber: 262),
  QuranSurah(number: 16, name: "النحل", pageNumber: 267),
  QuranSurah(number: 17, name: "الإسراء", pageNumber: 282),
  QuranSurah(number: 18, name: "الكهف", pageNumber: 293),
  QuranSurah(number: 19, name: "مريم", pageNumber: 305),
  QuranSurah(number: 20, name: "طه", pageNumber: 312),
  QuranSurah(number: 21, name: "الأنبياء", pageNumber: 322),
  QuranSurah(number: 22, name: "الحج", pageNumber: 332),
  QuranSurah(number: 23, name: "المؤمنون", pageNumber: 342),
  QuranSurah(number: 24, name: "النور", pageNumber: 350),
  QuranSurah(number: 25, name: "الفرقان", pageNumber: 359),
  QuranSurah(number: 26, name: "الشعراء", pageNumber: 367),
  QuranSurah(number: 27, name: "النمل", pageNumber: 377),
  QuranSurah(number: 28, name: "القصص", pageNumber: 385),
  QuranSurah(number: 29, name: "العنكبوت", pageNumber: 396),
  QuranSurah(number: 30, name: "الروم", pageNumber: 404),
  QuranSurah(number: 31, name: "لقمان", pageNumber: 411),
  QuranSurah(number: 32, name: "السجدة", pageNumber: 415),
  QuranSurah(number: 33, name: "الأحزاب", pageNumber: 418),
  QuranSurah(number: 34, name: "سبأ", pageNumber: 428),
  QuranSurah(number: 35, name: "فاطر", pageNumber: 434),
  QuranSurah(number: 36, name: "يس", pageNumber: 440),
  QuranSurah(number: 37, name: "الصافات", pageNumber: 446),
  QuranSurah(number: 38, name: "ص", pageNumber: 453),
  QuranSurah(number: 39, name: "الزمر", pageNumber: 458),
  QuranSurah(number: 40, name: "غافر", pageNumber: 467),
  QuranSurah(number: 41, name: "فصلت", pageNumber: 477),
  QuranSurah(number: 42, name: "الشورى", pageNumber: 483),
  QuranSurah(number: 43, name: "الزخرف", pageNumber: 489),
  QuranSurah(number: 44, name: "الدخان", pageNumber: 496),
  QuranSurah(number: 45, name: "الجاثية", pageNumber: 499),
  QuranSurah(number: 46, name: "الأحقاف", pageNumber: 502),
  QuranSurah(number: 47, name: "محمد", pageNumber: 507),
  QuranSurah(number: 48, name: "الفتح", pageNumber: 511),
  QuranSurah(number: 49, name: "الحجرات", pageNumber: 515),
  QuranSurah(number: 50, name: "ق", pageNumber: 518),
  QuranSurah(number: 51, name: "الذاريات", pageNumber: 520),
  QuranSurah(number: 52, name: "الطور", pageNumber: 523),
  QuranSurah(number: 53, name: "النجم", pageNumber: 526),
  QuranSurah(number: 54, name: "القمر", pageNumber: 528),
  QuranSurah(number: 55, name: "الرحمن", pageNumber: 531),
  QuranSurah(number: 56, name: "الواقعة", pageNumber: 534),
  QuranSurah(number: 57, name: "الحديد", pageNumber: 537),
  QuranSurah(number: 58, name: "المجادلة", pageNumber: 542),
  QuranSurah(number: 59, name: "الحشر", pageNumber: 545),
  QuranSurah(number: 60, name: "الممتحنة", pageNumber: 549),
  QuranSurah(number: 61, name: "الصف", pageNumber: 551),
  QuranSurah(number: 62, name: "الجمعة", pageNumber: 553),
  QuranSurah(number: 63, name: "المنافقون", pageNumber: 554),
  QuranSurah(number: 64, name: "التغابن", pageNumber: 556),
  QuranSurah(number: 65, name: "الطلاق", pageNumber: 558),
  QuranSurah(number: 66, name: "التحريم", pageNumber: 560),
  QuranSurah(number: 67, name: "الملك", pageNumber: 562),
  QuranSurah(number: 68, name: "القلم", pageNumber: 564),
  QuranSurah(number: 69, name: "الحاقة", pageNumber: 566),
  QuranSurah(number: 70, name: "المعارج", pageNumber: 568),
  QuranSurah(number: 71, name: "نوح", pageNumber: 570),
  QuranSurah(number: 72, name: "الجن", pageNumber: 572),
  QuranSurah(number: 73, name: "المزمل", pageNumber: 574),
  QuranSurah(number: 74, name: "المدثر", pageNumber: 575),
  QuranSurah(number: 75, name: "القيامة", pageNumber: 577),
  QuranSurah(number: 76, name: "الإنسان", pageNumber: 578),
  QuranSurah(number: 77, name: "المرسلات", pageNumber: 580),
  QuranSurah(number: 78, name: "النبأ", pageNumber: 582),
  QuranSurah(number: 79, name: "النازعات", pageNumber: 583),
  QuranSurah(number: 80, name: "عبس", pageNumber: 585),
  QuranSurah(number: 81, name: "التكوير", pageNumber: 586),
  QuranSurah(number: 82, name: "الإنفطار", pageNumber: 587),
  QuranSurah(number: 83, name: "المطففين", pageNumber: 587),
  QuranSurah(number: 84, name: "الإنشقاق", pageNumber: 589),
  QuranSurah(number: 85, name: "البروج", pageNumber: 590),
  QuranSurah(number: 86, name: "الطارق", pageNumber: 591),
  QuranSurah(number: 87, name: "الأعلى", pageNumber: 591),
  QuranSurah(number: 88, name: "الغاشية", pageNumber: 592),
  QuranSurah(number: 89, name: "الفجر", pageNumber: 593),
  QuranSurah(number: 90, name: "البلد", pageNumber: 594),
  QuranSurah(number: 91, name: "الشمس", pageNumber: 595),
  QuranSurah(number: 92, name: "الليل", pageNumber: 595),
  QuranSurah(number: 93, name: "الضحى", pageNumber: 596),
  QuranSurah(number: 94, name: "الشرح", pageNumber: 596),
  QuranSurah(number: 95, name: "التين", pageNumber: 597),
  QuranSurah(number: 96, name: "العلق", pageNumber: 597),
  QuranSurah(number: 97, name: "القدر", pageNumber: 598),
  QuranSurah(number: 98, name: "البينة", pageNumber: 598),
  QuranSurah(number: 99, name: "الزلزلة", pageNumber: 599),
  QuranSurah(number: 100, name: "العاديات", pageNumber: 599),
  QuranSurah(number: 101, name: "القارعة", pageNumber: 600),
  QuranSurah(number: 102, name: "التكاثر", pageNumber: 600),
  QuranSurah(number: 103, name: "العصر", pageNumber: 601),
  QuranSurah(number: 104, name: "الهمزة", pageNumber: 601),
  QuranSurah(number: 105, name: "الفيل", pageNumber: 601),
  QuranSurah(number: 106, name: "قريش", pageNumber: 602),
  QuranSurah(number: 107, name: "الماعون", pageNumber: 602),
  QuranSurah(number: 108, name: "الكوثر", pageNumber: 602),
  QuranSurah(number: 109, name: "الكافرون", pageNumber: 603),
  QuranSurah(number: 110, name: "النصر", pageNumber: 603),
  QuranSurah(number: 111, name: "المسد", pageNumber: 603),
  QuranSurah(number: 112, name: "الإخلاص", pageNumber: 604),
  QuranSurah(number: 113, name: "الفلق", pageNumber: 604),
  QuranSurah(number: 114, name: "الناس", pageNumber: 604),
];
